# down.yaml
- name: Remove Jenkins from k8s
  hosts: localhost
  gather_facts: false

  vars:
    kubeconfig: "{{ lookup('env','KUBECONFIG') | default('~/.kube/config', true) }}"
    ns: jenkins

  tasks:
    - name: Delete Ingress (if present)
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        api_version: networking.k8s.io/v1
        kind: Ingress
        namespace: "{{ ns }}"
        name: jenkins

    - name: Delete JNLP service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        api_version: v1
        kind: Service
        namespace: "{{ ns }}"
        name: jenkins-jnlp

    - name: Delete UI service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        api_version: v1
        kind: Service
        namespace: "{{ ns }}"
        name: jenkins

    - name: Delete Deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        api_version: apps/v1
        kind: Deployment
        namespace: "{{ ns }}"
        name: jenkins

    - name: Delete Namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: absent
        api_version: v1
        kind: Namespace
        name: "{{ ns }}"
